"""add cents columns to lesson and backfill

Revision ID: 02c515f814a9
Revises: 
Create Date: 2025-09-25 07:27:52.474800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02c515f814a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_rate_cents', sa.Integer(), server_default='11000', nullable=False))
        batch_op.add_column(sa.Column('hourly_rate_at_time_cents', sa.Integer(), server_default='11000', nullable=False))
        batch_op.drop_column('hourly_rate_at_time')
        batch_op.drop_column('hourly_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lesson', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hourly_rate', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('hourly_rate_at_time', sa.FLOAT(), nullable=False))
        batch_op.drop_column('hourly_rate_at_time_cents')
        batch_op.drop_column('hourly_rate_cents')

    # ### end Alembic commands ###
