name: Build & Push images (after CI success)

on:
  workflow_run:
    workflows: ["CI (Compose + E2E)"]
    types: [completed]

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/pro_dev

    strategy:
      matrix:
        service:
          - { name: backend,  dockerfile: Dockerfile.backend }
          - { name: frontend, dockerfile: Dockerfile.frontend }

    steps:
      - name: Checkout the exact commit from CI
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (single repo / multi tags)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: |
            ${{ env.DOCKER_IMAGE }}:${{ matrix.service.name }}-latest
            ${{ env.DOCKER_IMAGE }}:${{ matrix.service.name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
